### ISSUE TITLE
Image build takes time when build context is big

### ISSUE THREAD

**Issue by ricardaxel** [vv9k/docker-api-rs#39] opened 2022-12-23 13:00 UTC
- Crate version: tested on c58eed7c12b47a4c9963271c80a2e347de6d7b04
- OS: debian bullseye
- Output of running `docker version` on the command line:
```
Client: Docker Engine - Community
 Version:           20.10.21
 API version:       1.41
 Go version:        go1.18.7
 Git commit:        baeda1f
 Built:             Tue Oct 25 18:02:28 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.21
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.7
  Git commit:       3056208
  Built:            Tue Oct 25 18:00:19 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.9
  GitCommit:        1c90a442489720eec95342e1789ee8a5e1b9536f
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

Hello, I tried to build a docker image with the example :  `cargo run --example image -- build .`

This succeeds but it takes a very long time (~50 minutes), even with a simple Dockerfile. After some investigation, it seems that this is the sending of build context to the daemon that slows down the build. 
For my test, I had the Dockerfile at the root of this repo, so it had to send ~1.8Gb of build context.
Doing the same test with the Dockerfile in an empty directory, the build is almost immediate.

Do you have any hint to reduce the build time when the build context is big ?

**Comment by ricardaxel** [comment] 2022-12-23 13:46
With ~1.8Gb build context : 
![image](https://user-images.githubusercontent.com/46921637/209346035-3cb9347f-a85a-4401-8fe0-ed5d801e8290.png)

Without build context :
![image](https://user-images.githubusercontent.com/46921637/209346101-412dc9c1-2d73-4862-957c-2338d62f9903.png)

**Comment by vv9k** [comment] 2022-12-25 06:10
Hello, thanks for the report! I've tried doing some tests locally but couldn't reproduce. What type of files are in your build context directory? Are there many small files perhaps or a lot of large ones?

I've tried two scenarios:
 * A big file >2Gb and it took around a minute to handle it
 * A lot of small files, in my test i used 20000 100Kb files (~2Gb) and it took 1m38.769s

**Comment by ricardaxel** [comment] 2022-12-25 18:11
I have a HDD. It takes a little more time in my computer, but way more time than a `docker build`

I made a little script to reproduce some situations, you can check it there : https://github.com/ricardaxel/docker-api-rs

In my laptop, I got the following results :

```
--- NO BUILD CONTEXT ---                                                                                                                                                    
---> docker                                                                                                                                                                 
                                                                                                                                                                            
real    0m0.184s                                                                                                                                                            
user    0m0.024s                                                                                                                                                            
sys     0m0.010s                                                                                                                                                            

---> docker-api

real    0m0.241s
user    0m0.017s
sys     0m0.009s

--- 20000 FILES; 100Kb EACH ---
---> docker

real    0m11.463s
user    0m1.794s
sys     0m4.001s

---> docker-api

real    2m33.577s
user    2m20.589s
sys     0m0.520s

--- 1 FILE; 2Gb ---
---> docker

real    0m10.826s
user    0m1.612s
sys     0m4.405s

---> docker-api

real    2m25.110s
user    2m12.352s
sys     0m0.519s

--- THIS REPO AS BUILD CONTEXT ---
---> docker

real    0m28.719s
user    0m4.438s
sys     0m8.596s

---> docker-api

real    50m15.790s
```

**Comment by vv9k** [comment] 2022-12-25 20:40
Try building with `--release` flag, it should speed up the time significantly. It's still way behind docker-cli when using this repo as build contenxt but in other scenarios it works reasonably well.

Here are my results with `--release`:
```
--- NO BUILD CONTEXT ---
---> docker

real    0m0.036s
user    0m0.010s
sys     0m0.005s

---> docker-api

real    0m0.030s
user    0m0.004s
sys     0m0.000s

--- 20000 FILES; 100Kb EACH ---
---> docker

real    0m1.857s
user    0m0.222s
sys     0m0.496s

---> docker-api

real    0m3.674s
user    0m1.649s
sys     0m0.120s

--- 1 FILE; 2Gb ---
---> docker

real    0m4.747s
user    0m0.486s
sys     0m1.200s

---> docker-api

real    0m9.932s
user    0m4.688s
sys     0m0.370s

--- THIS REPO AS BUILD CONTEXT ---
---> docker

real    0m14.051s
user    0m1.370s
sys     0m4.123s

---> docker-api

real    3m33.318s
user    3m9.899s
sys     0m1.346s
```

The biggest difference is that docker-cli uses goroutines to append to the archive which can be seen [here](https://github.com/docker/cli/blob/139e924690b9b3f5e49c86d93a4025da9d47c6a9/vendor/github.com/docker/docker/pkg/archive/archive.go#L852) . This should be possible in some way using [gzp](https://github.com/sstadick/gzp) but I haven't yet found a way to integrate it as the ParCompressBuilder requires the write buffer to be static.

**Comment by ricardaxel** [comment] 2022-12-28 11:29
Indeed the static lifetime makes things harder.  
Correct me if I'm wrong, but it seems that gzp is designed to write output in a file or to stdout. Wouldn't it be possible to do some pipe/fifo manipulation as a workaround to this static liftetime ?

**Comment by vv9k** [comment] 2023-01-09 06:11
Sorry for the late response, I'm very busy recently and don't have much time to code or check github unfortunatelly.

> Indeed the static lifetime makes things harder. Correct me if I'm wrong, but it seems that gzp is designed to write output in a file or to stdout. Wouldn't it be possible to do some pipe/fifo manipulation as a workaround to this static liftetime ?

It does seem like a viable solution but I don't have much experience with pipe/fifo and this solution would also probably have to be handled on different operating systems which could take some time (that I currently don't have). It should also probably be behind a feature flag so that `gzp` doesn't get pulled unless the feature is on.

**Comment by vv9k** [comment] 2023-02-16 05:47
Managed to find some time to look into this and got promissing results using memfile. The speedup for this repo as build context is around 4x on my computer and is now much closer to docker-cli. I still have to cleanup the changes and put them behind a feature gate but should be merged soon :). Below are the times of reproduce with `docker` as baseline, `docker-api` as the default and `docker-api-multi` as the new multithreaded option.

```
--- NO BUILD CONTEXT ---
---> docker

real    0m0.038s
user    0m0.004s
sys     0m0.015s

---> docker-api

real    0m0.029s
user    0m0.004s
sys     0m0.000s

---> docker-api-multi

real    0m0.029s
user    0m0.007s
sys     0m0.000s
```
```
--- 20000 FILES; 100Kb EACH ---
---> docker

real    0m1.770s
user    0m0.282s
sys     0m0.342s

---> docker-api

real    0m3.437s
user    0m1.471s
sys     0m0.119s

---> docker-api-multi

real    0m2.101s
user    0m0.915s
sys     0m0.146s
```
```
--- 1 FILE; 2Gb ---
---> docker

real    0m4.750s
user    0m0.549s
sys     0m1.000s

---> docker-api

real    0m8.704s
user    0m3.615s
sys     0m0.235s

---> docker-api-multi

real    0m5.727s
user    0m2.745s
sys     0m0.458s
```
```
--- THIS REPO AS BUILD CONTEXT ---
---> docker

real    0m22.639s
user    0m2.250s
sys     0m4.410s

---> docker-api

real    4m8.256s
user    3m22.995s
sys     0m2.087s

---> docker-api-multi

real    0m54.507s
user    1m32.582s
sys     0m4.549s
```

**Closed** 2023-02-19 05:47 UTC
